// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: DataGathering

#ifndef UI_DATA_H
#define UI_DATA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Data
extern void ui_Data_screen_init(void);
extern void ui_Data_screen_destroy(void);
extern lv_obj_t * ui_Data;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Chart1_Xaxis;
extern lv_obj_t * ui_Chart1_Yaxis1;
extern lv_obj_t * ui_Chart1_Yaxis2;
extern lv_obj_t * ui_FlowRate;
extern lv_obj_t * ui_lblFlowRate;
extern lv_obj_t * ui_lblFlowRateValue;
extern lv_obj_t * ui_Voltage;
extern lv_obj_t * ui_lblVoltage;
extern lv_obj_t * ui_lblVoltageValue;
extern lv_obj_t * ui_Ampere;
extern lv_obj_t * ui_lblAmpere;
extern lv_obj_t * ui_lblAmpereValue;
extern lv_obj_t * ui_Power;
extern lv_obj_t * ui_lblPower;
extern lv_obj_t * ui_lblPowerValue;
extern lv_obj_t * ui_RPM;
extern lv_obj_t * ui_lblRpm;
extern lv_obj_t * ui_lblRpmValue;
extern void ui_event_btnDataBack(lv_event_t * e);
extern lv_obj_t * ui_btnDataBack;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Data;
extern lv_obj_t * uic_FlowRate;
extern lv_obj_t * uic_lblFlowRate;
extern lv_obj_t * uic_lblFlowRateValue;
extern lv_obj_t * uic_Voltage;
extern lv_obj_t * uic_lblVoltage;
extern lv_obj_t * uic_lblVoltageValue;
extern lv_obj_t * uic_Ampere;
extern lv_obj_t * uic_lblAmpere;
extern lv_obj_t * uic_lblAmpereValue;
extern lv_obj_t * uic_Power;
extern lv_obj_t * uic_lblPower;
extern lv_obj_t * uic_lblPowerValue;
extern lv_obj_t * uic_RPM;
extern lv_obj_t * uic_lblRpm;
extern lv_obj_t * uic_lblRpmValue;
extern lv_obj_t * uic_btnDataBack;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

