// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: DataGathering

#include "ui.h"

lv_obj_t * uic_lblTimeValue;
lv_obj_t * uic_btnDataBack;
lv_obj_t * uic_lblRpmValue;
lv_obj_t * uic_lblRpm;
lv_obj_t * uic_RPM;
lv_obj_t * uic_lblPowerValue;
lv_obj_t * uic_lblPower;
lv_obj_t * uic_Power;
lv_obj_t * uic_lblAmpereValue;
lv_obj_t * uic_lblAmpere;
lv_obj_t * uic_Ampere;
lv_obj_t * uic_lblVoltageValue;
lv_obj_t * uic_lblVoltage;
lv_obj_t * uic_Voltage;
lv_obj_t * uic_lblFlowRateValue;
lv_obj_t * uic_lblFlowRate;
lv_obj_t * uic_FlowRate;
lv_obj_t * uic_Data;
lv_obj_t * ui_Data = NULL;
lv_obj_t * ui_Chart1 = NULL;
lv_obj_t * ui_Chart1_Xaxis = NULL;
lv_obj_t * ui_Chart1_Yaxis1 = NULL;
lv_obj_t * ui_Chart1_Yaxis2 = NULL;
lv_obj_t * ui_FlowRate = NULL;
lv_obj_t * ui_lblFlowRate = NULL;
lv_obj_t * ui_lblFlowRateValue = NULL;
lv_obj_t * ui_Voltage = NULL;
lv_obj_t * ui_lblVoltage = NULL;
lv_obj_t * ui_lblVoltageValue = NULL;
lv_obj_t * ui_Ampere = NULL;
lv_obj_t * ui_lblAmpere = NULL;
lv_obj_t * ui_lblAmpereValue = NULL;
lv_obj_t * ui_Power = NULL;
lv_obj_t * ui_lblPower = NULL;
lv_obj_t * ui_lblPowerValue = NULL;
lv_obj_t * ui_RPM = NULL;
lv_obj_t * ui_lblRpm = NULL;
lv_obj_t * ui_lblRpmValue = NULL;
lv_obj_t * ui_btnDataBack = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_RPM1 = NULL;
lv_obj_t * ui_lblRpm1 = NULL;
lv_obj_t * ui_lblTimeValue = NULL;
// event funtions
void ui_event_btnDataBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_MainMenu_screen_init);
    }
}

// build funtions

void ui_Data_screen_init(void)
{
    ui_Data = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Data, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart1 = lv_chart_create(ui_Data);
    lv_obj_set_width(ui_Chart1, 650);
    lv_obj_set_height(ui_Chart1, 520);
    lv_obj_set_x(ui_Chart1, -142);
    lv_obj_set_y(ui_Chart1, 0);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Chart1, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart1, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 50);
    lv_chart_set_range(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 50);

    ui_Chart1_Xaxis = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart1_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart1_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart1_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart1_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart1_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart1_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart1_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Xaxis, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_Chart1_Xaxis, false);
    ui_Chart1_Yaxis1 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart1_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart1,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart1_Yaxis1,  0, 50);
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart1_Yaxis2 = lv_scale_create(ui_Chart1);
    lv_scale_set_mode(ui_Chart1_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart1_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart1_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart1_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart1,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart1, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart1_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart1_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart1_Yaxis2,  0, 50);
    lv_scale_set_total_tick_count(ui_Chart1_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart1_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xF60707),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 0, 0, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);
    lv_chart_series_t * ui_Chart1_series_2 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x0D06E9),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_2_array[] = { 0, 10, 20, 40, 0, 0, 0, 40, 20, 10, 0, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_2, ui_Chart1_series_2_array);
    lv_chart_series_t * ui_Chart1_series_3 = lv_chart_add_series(ui_Chart1, lv_color_hex(0xF3E913),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart1_series_3_array[] = { 0, 10, 20, 40, 0, 20, 40, 20, 10, 0, 10 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_3, ui_Chart1_series_3_array);
    lv_chart_series_t * ui_Chart1_series_4 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart1_series_4_array[] = { 0, 10, 20, 2, 0, 0, 0, 40, 20, 10, 0, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_4, ui_Chart1_series_4_array);

    lv_obj_set_style_line_width(ui_Chart1, 5, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_Chart1, true, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_outline_color(ui_Chart1, lv_color_hex(0x010101), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Chart1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Chart1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Chart1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_Chart1, 10, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Chart1_Xaxis, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart1_Xaxis, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart1_Yaxis1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart1_Yaxis1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Chart1_Yaxis2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Chart1_Yaxis2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Chart1_Xaxis, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Chart1_Yaxis1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Chart1_Yaxis2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chart1_Xaxis, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chart1_Yaxis1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Chart1_Yaxis2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart1, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart1, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_FlowRate = lv_obj_create(ui_Data);
    lv_obj_remove_style_all(ui_FlowRate);
    lv_obj_set_width(ui_FlowRate, 194);
    lv_obj_set_height(ui_FlowRate, 45);
    lv_obj_set_x(ui_FlowRate, 360);
    lv_obj_set_y(ui_FlowRate, -240);
    lv_obj_set_align(ui_FlowRate, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_FlowRate, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblFlowRate = lv_label_create(ui_FlowRate);
    lv_obj_set_width(ui_lblFlowRate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFlowRate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFlowRate, 0);
    lv_obj_set_y(ui_lblFlowRate, -13);
    lv_obj_set_align(ui_lblFlowRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblFlowRate, "FLOW RATE");
    lv_obj_set_style_text_font(ui_lblFlowRate, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblFlowRateValue = lv_label_create(ui_FlowRate);
    lv_obj_set_width(ui_lblFlowRateValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblFlowRateValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblFlowRateValue, 0);
    lv_obj_set_y(ui_lblFlowRateValue, 15);
    lv_obj_set_align(ui_lblFlowRateValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblFlowRateValue, "5.5 L/M");
    lv_obj_set_style_text_font(ui_lblFlowRateValue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Voltage = lv_obj_create(ui_Data);
    lv_obj_remove_style_all(ui_Voltage);
    lv_obj_set_width(ui_Voltage, 194);
    lv_obj_set_height(ui_Voltage, 45);
    lv_obj_set_x(ui_Voltage, 360);
    lv_obj_set_y(ui_Voltage, -180);
    lv_obj_set_align(ui_Voltage, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Voltage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblVoltage = lv_label_create(ui_Voltage);
    lv_obj_set_width(ui_lblVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblVoltage, 0);
    lv_obj_set_y(ui_lblVoltage, -13);
    lv_obj_set_align(ui_lblVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVoltage, "VOLTAGE");
    lv_obj_set_style_text_font(ui_lblVoltage, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVoltageValue = lv_label_create(ui_Voltage);
    lv_obj_set_width(ui_lblVoltageValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblVoltageValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblVoltageValue, 0);
    lv_obj_set_y(ui_lblVoltageValue, 15);
    lv_obj_set_align(ui_lblVoltageValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVoltageValue, "10.0 V");
    lv_obj_set_style_text_font(ui_lblVoltageValue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Ampere = lv_obj_create(ui_Data);
    lv_obj_remove_style_all(ui_Ampere);
    lv_obj_set_width(ui_Ampere, 194);
    lv_obj_set_height(ui_Ampere, 45);
    lv_obj_set_x(ui_Ampere, 360);
    lv_obj_set_y(ui_Ampere, -120);
    lv_obj_set_align(ui_Ampere, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Ampere, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblAmpere = lv_label_create(ui_Ampere);
    lv_obj_set_width(ui_lblAmpere, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblAmpere, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAmpere, 0);
    lv_obj_set_y(ui_lblAmpere, -13);
    lv_obj_set_align(ui_lblAmpere, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblAmpere, "AMPERE");
    lv_obj_set_style_text_font(ui_lblAmpere, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblAmpereValue = lv_label_create(ui_Ampere);
    lv_obj_set_width(ui_lblAmpereValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblAmpereValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAmpereValue, 0);
    lv_obj_set_y(ui_lblAmpereValue, 15);
    lv_obj_set_align(ui_lblAmpereValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblAmpereValue, "2.1 A");
    lv_obj_set_style_text_font(ui_lblAmpereValue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Power = lv_obj_create(ui_Data);
    lv_obj_remove_style_all(ui_Power);
    lv_obj_set_width(ui_Power, 194);
    lv_obj_set_height(ui_Power, 45);
    lv_obj_set_x(ui_Power, 360);
    lv_obj_set_y(ui_Power, -60);
    lv_obj_set_align(ui_Power, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Power, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblPower = lv_label_create(ui_Power);
    lv_obj_set_width(ui_lblPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPower, 0);
    lv_obj_set_y(ui_lblPower, -13);
    lv_obj_set_align(ui_lblPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPower, "POWER");
    lv_obj_set_style_text_font(ui_lblPower, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblPowerValue = lv_label_create(ui_Power);
    lv_obj_set_width(ui_lblPowerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblPowerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblPowerValue, 0);
    lv_obj_set_y(ui_lblPowerValue, 15);
    lv_obj_set_align(ui_lblPowerValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblPowerValue, "50 W");
    lv_obj_set_style_text_font(ui_lblPowerValue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPM = lv_obj_create(ui_Data);
    lv_obj_remove_style_all(ui_RPM);
    lv_obj_set_width(ui_RPM, 194);
    lv_obj_set_height(ui_RPM, 45);
    lv_obj_set_x(ui_RPM, 360);
    lv_obj_set_y(ui_RPM, 0);
    lv_obj_set_align(ui_RPM, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RPM, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblRpm = lv_label_create(ui_RPM);
    lv_obj_set_width(ui_lblRpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRpm, 0);
    lv_obj_set_y(ui_lblRpm, -13);
    lv_obj_set_align(ui_lblRpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRpm, "RPM");
    lv_obj_set_style_text_font(ui_lblRpm, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRpmValue = lv_label_create(ui_RPM);
    lv_obj_set_width(ui_lblRpmValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRpmValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRpmValue, 0);
    lv_obj_set_y(ui_lblRpmValue, 15);
    lv_obj_set_align(ui_lblRpmValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRpmValue, "800 RPM");
    lv_obj_set_style_text_font(ui_lblRpmValue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnDataBack = lv_button_create(ui_Data);
    lv_obj_set_width(ui_btnDataBack, 250);
    lv_obj_set_height(ui_btnDataBack, 100);
    lv_obj_set_x(ui_btnDataBack, 354);
    lv_obj_set_y(ui_btnDataBack, 211);
    lv_obj_set_align(ui_btnDataBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnDataBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnDataBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnDataBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnDataBack, lv_color_hex(0xD34D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnDataBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnDataBack, lv_color_hex(0x891818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnDataBack, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnDataBack, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnDataBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnDataBack, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnDataBack, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnDataBack, lv_color_hex(0xAD7171), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnDataBack, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnDataBack, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnDataBack, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_btnDataBack, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_btnDataBack, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnDataBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btnDataBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_btnDataBack, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_btnDataBack, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_btnDataBack);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "BACK");

    ui_RPM1 = lv_obj_create(ui_Data);
    lv_obj_remove_style_all(ui_RPM1);
    lv_obj_set_width(ui_RPM1, 194);
    lv_obj_set_height(ui_RPM1, 45);
    lv_obj_set_x(ui_RPM1, 360);
    lv_obj_set_y(ui_RPM1, 60);
    lv_obj_set_align(ui_RPM1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RPM1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblRpm1 = lv_label_create(ui_RPM1);
    lv_obj_set_width(ui_lblRpm1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblRpm1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRpm1, 0);
    lv_obj_set_y(ui_lblRpm1, -13);
    lv_obj_set_align(ui_lblRpm1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRpm1, "Time");
    lv_obj_set_style_text_font(ui_lblRpm1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTimeValue = lv_label_create(ui_RPM1);
    lv_obj_set_width(ui_lblTimeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTimeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTimeValue, 0);
    lv_obj_set_y(ui_lblTimeValue, 15);
    lv_obj_set_align(ui_lblTimeValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTimeValue, "Current Time");
    lv_obj_set_style_text_font(ui_lblTimeValue, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnDataBack, ui_event_btnDataBack, LV_EVENT_ALL, NULL);
    uic_Data = ui_Data;
    uic_FlowRate = ui_FlowRate;
    uic_lblFlowRate = ui_lblFlowRate;
    uic_lblFlowRateValue = ui_lblFlowRateValue;
    uic_Voltage = ui_Voltage;
    uic_lblVoltage = ui_lblVoltage;
    uic_lblVoltageValue = ui_lblVoltageValue;
    uic_Ampere = ui_Ampere;
    uic_lblAmpere = ui_lblAmpere;
    uic_lblAmpereValue = ui_lblAmpereValue;
    uic_Power = ui_Power;
    uic_lblPower = ui_lblPower;
    uic_lblPowerValue = ui_lblPowerValue;
    uic_RPM = ui_RPM;
    uic_lblRpm = ui_lblRpm;
    uic_lblRpmValue = ui_lblRpmValue;
    uic_btnDataBack = ui_btnDataBack;
    uic_lblTimeValue = ui_lblTimeValue;

}

void ui_Data_screen_destroy(void)
{
    if(ui_Data) lv_obj_del(ui_Data);

    // NULL screen variables
    uic_Data = NULL;
    ui_Data = NULL;
    ui_Chart1 = NULL;
    uic_FlowRate = NULL;
    ui_FlowRate = NULL;
    uic_lblFlowRate = NULL;
    ui_lblFlowRate = NULL;
    uic_lblFlowRateValue = NULL;
    ui_lblFlowRateValue = NULL;
    uic_Voltage = NULL;
    ui_Voltage = NULL;
    uic_lblVoltage = NULL;
    ui_lblVoltage = NULL;
    uic_lblVoltageValue = NULL;
    ui_lblVoltageValue = NULL;
    uic_Ampere = NULL;
    ui_Ampere = NULL;
    uic_lblAmpere = NULL;
    ui_lblAmpere = NULL;
    uic_lblAmpereValue = NULL;
    ui_lblAmpereValue = NULL;
    uic_Power = NULL;
    ui_Power = NULL;
    uic_lblPower = NULL;
    ui_lblPower = NULL;
    uic_lblPowerValue = NULL;
    ui_lblPowerValue = NULL;
    uic_RPM = NULL;
    ui_RPM = NULL;
    uic_lblRpm = NULL;
    ui_lblRpm = NULL;
    uic_lblRpmValue = NULL;
    ui_lblRpmValue = NULL;
    uic_btnDataBack = NULL;
    ui_btnDataBack = NULL;
    ui_Label8 = NULL;
    ui_RPM1 = NULL;
    ui_lblRpm1 = NULL;
    uic_lblTimeValue = NULL;
    ui_lblTimeValue = NULL;

}
