// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: DataGathering

#ifndef UI_GAUGES_H
#define UI_GAUGES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Gauges
extern void ui_Gauges_screen_init(void);
extern void ui_Gauges_screen_destroy(void);
extern lv_obj_t * ui_Gauges;
extern lv_obj_t * ui_gVoltage;
extern lv_obj_t * ui_gVoltageValue;
extern lv_obj_t * ui_titVoltage;
extern lv_obj_t * ui_gAmpere;
extern lv_obj_t * ui_gAmpereValue;
extern lv_obj_t * ui_titAmpere;
extern lv_obj_t * ui_gRPM;
extern lv_obj_t * ui_gRpmValue;
extern lv_obj_t * ui_titRpm;
extern lv_obj_t * ui_gPower;
extern lv_obj_t * ui_gPowerValue;
extern lv_obj_t * ui_titPower;
extern lv_obj_t * ui_gWaterFlow;
extern lv_obj_t * ui_gWaterFlowValue;
extern lv_obj_t * ui_titWaterFlow;
extern void ui_event_btnGaugeBack(lv_event_t * e);
extern lv_obj_t * ui_btnGaugeBack;
extern lv_obj_t * ui_Label6;
extern void ui_event_btnGaugeData(lv_event_t * e);
extern lv_obj_t * ui_btnGaugeData;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Gauges;
extern lv_obj_t * uic_gVoltage;
extern lv_obj_t * uic_gVoltageValue;
extern lv_obj_t * uic_titVoltage;
extern lv_obj_t * uic_gAmpere;
extern lv_obj_t * uic_gAmpereValue;
extern lv_obj_t * uic_titAmpere;
extern lv_obj_t * uic_gRPM;
extern lv_obj_t * uic_gRpmValue;
extern lv_obj_t * uic_titRpm;
extern lv_obj_t * uic_gPower;
extern lv_obj_t * uic_gPowerValue;
extern lv_obj_t * uic_titPower;
extern lv_obj_t * uic_gWaterFlow;
extern lv_obj_t * uic_gWaterFlowValue;
extern lv_obj_t * uic_titWaterFlow;
extern lv_obj_t * uic_btnGaugeBack;
extern lv_obj_t * uic_btnGaugeData;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

