// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: DataGathering

#include "ui.h"
#include "gauges_controller.h"

lv_obj_t * uic_btnGaugeData;
lv_obj_t * uic_btnGaugeBack;
lv_obj_t * uic_titWaterFlow;
lv_obj_t * uic_gWaterFlowValue;
lv_obj_t * uic_gWaterFlow;
lv_obj_t * uic_titPower;
lv_obj_t * uic_gPowerValue;
lv_obj_t * uic_gPower;
lv_obj_t * uic_titRpm;
lv_obj_t * uic_gRpmValue;
lv_obj_t * uic_gRPM;
lv_obj_t * uic_titAmpere;
lv_obj_t * uic_gAmpereValue;
lv_obj_t * uic_gAmpere;
lv_obj_t * uic_titVoltage;
lv_obj_t * uic_gVoltageValue;
lv_obj_t * uic_gVoltage;
lv_obj_t * uic_Gauges;
lv_obj_t * ui_Gauges = NULL;
lv_obj_t * ui_gVoltage = NULL;
lv_obj_t * ui_gVoltageValue = NULL;
lv_obj_t * ui_titVoltage = NULL;
lv_obj_t * ui_gAmpere = NULL;
lv_obj_t * ui_gAmpereValue = NULL;
lv_obj_t * ui_titAmpere = NULL;
lv_obj_t * ui_gRPM = NULL;
lv_obj_t * ui_gRpmValue = NULL;
lv_obj_t * ui_titRpm = NULL;
lv_obj_t * ui_gPower = NULL;
lv_obj_t * ui_gPowerValue = NULL;
lv_obj_t * ui_titPower = NULL;
lv_obj_t * ui_gWaterFlow = NULL;
lv_obj_t * ui_gWaterFlowValue = NULL;
lv_obj_t * ui_titWaterFlow = NULL;
lv_obj_t * ui_btnGaugeBack = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_btnGaugeData = NULL;
lv_obj_t * ui_Label5 = NULL;
// event funtions
void ui_event_btnGaugeBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_MainMenu_screen_init);
    }
}

void ui_event_btnGaugeData(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        gauges_controller_reset_chart();
        _ui_screen_change(&ui_Data, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Data_screen_init);
        gauges_controller_refresh_chart();
    }
}

// build funtions

void ui_Gauges_screen_init(void)
{
    ui_Gauges = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Gauges, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Gauges, lv_color_hex(0x0E0E1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gauges, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gVoltage = lv_arc_create(ui_Gauges);
    lv_obj_set_width(ui_gVoltage, 250);
    lv_obj_set_height(ui_gVoltage, 250);
    lv_obj_set_x(ui_gVoltage, -320);
    lv_obj_set_y(ui_gVoltage, -140);
    lv_obj_set_align(ui_gVoltage, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_gVoltage, 30);
    lv_obj_set_style_arc_color(ui_gVoltage, lv_color_hex(0x2D2D44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_gVoltage, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_gVoltage, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_gVoltage, lv_color_hex(0xF60707), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gVoltage, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_gVoltage, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gVoltage, lv_color_hex(0xF60707), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gVoltage, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_gVoltageValue = lv_label_create(ui_gVoltage);
    lv_obj_set_width(ui_gVoltageValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gVoltageValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gVoltageValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gVoltageValue, "22.1 V");
    lv_obj_set_style_text_font(ui_gVoltageValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_gVoltageValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titVoltage = lv_label_create(ui_gVoltage);
    lv_obj_set_width(ui_titVoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titVoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_titVoltage, 0);
    lv_obj_set_y(ui_titVoltage, 100);
    lv_obj_set_align(ui_titVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titVoltage, "Voltage");
    lv_obj_set_style_text_font(ui_titVoltage, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_titVoltage, lv_color_hex(0xF60707), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gAmpere = lv_arc_create(ui_Gauges);
    lv_obj_set_width(ui_gAmpere, 250);
    lv_obj_set_height(ui_gAmpere, 250);
    lv_obj_set_x(ui_gAmpere, 0);
    lv_obj_set_y(ui_gAmpere, -140);
    lv_obj_set_align(ui_gAmpere, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_gAmpere, 30);
    lv_obj_set_style_arc_color(ui_gAmpere, lv_color_hex(0x2D2D44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gAmpere, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_gAmpere, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_gAmpere, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_gAmpere, lv_color_hex(0x0D06E9), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gAmpere, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_gAmpere, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gAmpere, lv_color_hex(0x0D06E9), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gAmpere, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_gAmpereValue = lv_label_create(ui_gAmpere);
    lv_obj_set_width(ui_gAmpereValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gAmpereValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gAmpereValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gAmpereValue, "2.1 A");
    lv_obj_set_style_text_font(ui_gAmpereValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_gAmpereValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titAmpere = lv_label_create(ui_gAmpere);
    lv_obj_set_width(ui_titAmpere, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titAmpere, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_titAmpere, 0);
    lv_obj_set_y(ui_titAmpere, 100);
    lv_obj_set_align(ui_titAmpere, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titAmpere, "Ampere");
    lv_obj_set_style_text_font(ui_titAmpere, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_titAmpere, lv_color_hex(0x0D06E9), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gRPM = lv_arc_create(ui_Gauges);
    lv_obj_set_width(ui_gRPM, 250);
    lv_obj_set_height(ui_gRPM, 250);
    lv_obj_set_x(ui_gRPM, 320);
    lv_obj_set_y(ui_gRPM, -140);
    lv_obj_set_align(ui_gRPM, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_gRPM, 30);
    lv_obj_set_style_arc_color(ui_gRPM, lv_color_hex(0x2D2D44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gRPM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_gRPM, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_gRPM, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_gRPM, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gRPM, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_gRPM, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gRPM, lv_color_hex(0x808080), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gRPM, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_gRpmValue = lv_label_create(ui_gRPM);
    lv_obj_set_width(ui_gRpmValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gRpmValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gRpmValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gRpmValue, "800 RPM");
    lv_obj_set_style_text_font(ui_gRpmValue, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_gRpmValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titRpm = lv_label_create(ui_gRPM);
    lv_obj_set_width(ui_titRpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titRpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_titRpm, 0);
    lv_obj_set_y(ui_titRpm, 100);
    lv_obj_set_align(ui_titRpm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titRpm, "Speed");
    lv_obj_set_style_text_font(ui_titRpm, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_titRpm, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gPower = lv_arc_create(ui_Gauges);
    lv_obj_set_width(ui_gPower, 250);
    lv_obj_set_height(ui_gPower, 250);
    lv_obj_set_x(ui_gPower, -320);
    lv_obj_set_y(ui_gPower, 140);
    lv_obj_set_align(ui_gPower, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_gPower, 30);
    lv_obj_set_style_arc_color(ui_gPower, lv_color_hex(0x2D2D44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gPower, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_gPower, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_gPower, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_gPower, lv_color_hex(0x9B59B6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gPower, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_gPower, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gPower, lv_color_hex(0x9B59B6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gPower, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_gPowerValue = lv_label_create(ui_gPower);
    lv_obj_set_width(ui_gPowerValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gPowerValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gPowerValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gPowerValue, "100 W");
    lv_obj_set_style_text_font(ui_gPowerValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_gPowerValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titPower = lv_label_create(ui_gPower);
    lv_obj_set_width(ui_titPower, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titPower, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_titPower, 0);
    lv_obj_set_y(ui_titPower, 100);
    lv_obj_set_align(ui_titPower, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titPower, "Power");
    lv_obj_set_style_text_font(ui_titPower, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_titPower, lv_color_hex(0x9B59B6), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gWaterFlow = lv_arc_create(ui_Gauges);
    lv_obj_set_width(ui_gWaterFlow, 250);
    lv_obj_set_height(ui_gWaterFlow, 250);
    lv_obj_set_x(ui_gWaterFlow, 0);
    lv_obj_set_y(ui_gWaterFlow, 140);
    lv_obj_set_align(ui_gWaterFlow, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_gWaterFlow, 30);
    lv_obj_set_style_arc_color(ui_gWaterFlow, lv_color_hex(0x2D2D44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gWaterFlow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_gWaterFlow, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_gWaterFlow, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_gWaterFlow, lv_color_hex(0xF3E913), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_gWaterFlow, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_gWaterFlow, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_gWaterFlow, lv_color_hex(0xF3E913), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_gWaterFlow, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_gWaterFlowValue = lv_label_create(ui_gWaterFlow);
    lv_obj_set_width(ui_gWaterFlowValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gWaterFlowValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gWaterFlowValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_gWaterFlowValue, "5.5 L/M");
    lv_obj_set_style_text_font(ui_gWaterFlowValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_gWaterFlowValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_titWaterFlow = lv_label_create(ui_gWaterFlow);
    lv_obj_set_width(ui_titWaterFlow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_titWaterFlow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_titWaterFlow, 0);
    lv_obj_set_y(ui_titWaterFlow, 100);
    lv_obj_set_align(ui_titWaterFlow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_titWaterFlow, "Flow");
    lv_obj_set_style_text_font(ui_titWaterFlow, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_titWaterFlow, lv_color_hex(0xF3E913), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnGaugeBack = lv_button_create(ui_Gauges);
    lv_obj_set_width(ui_btnGaugeBack, 250);
    lv_obj_set_height(ui_btnGaugeBack, 100);
    lv_obj_set_x(ui_btnGaugeBack, 330);
    lv_obj_set_y(ui_btnGaugeBack, 75);
    lv_obj_set_align(ui_btnGaugeBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnGaugeBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnGaugeBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnGaugeBack, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnGaugeBack, lv_color_hex(0x1A1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnGaugeBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnGaugeBack, lv_color_hex(0xD34D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnGaugeBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnGaugeBack, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnGaugeBack, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnGaugeBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnGaugeBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btnGaugeBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_btnGaugeBack, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_btnGaugeBack, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnGaugeBack, lv_color_hex(0x2D2D44), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnGaugeBack, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label6 = lv_label_create(ui_btnGaugeBack);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "BACK");

    ui_btnGaugeData = lv_button_create(ui_Gauges);
    lv_obj_set_width(ui_btnGaugeData, 250);
    lv_obj_set_height(ui_btnGaugeData, 100);
    lv_obj_set_x(ui_btnGaugeData, 330);
    lv_obj_set_y(ui_btnGaugeData, 200);
    lv_obj_set_align(ui_btnGaugeData, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnGaugeData, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnGaugeData, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnGaugeData, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnGaugeData, lv_color_hex(0x1A1A2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnGaugeData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnGaugeData, lv_color_hex(0x4D7DD3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnGaugeData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnGaugeData, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnGaugeData, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnGaugeData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnGaugeData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btnGaugeData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_btnGaugeData, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_btnGaugeData, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnGaugeData, lv_color_hex(0x2D2D44), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_btnGaugeData, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label5 = lv_label_create(ui_btnGaugeData);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "DATA");

    lv_obj_add_event_cb(ui_btnGaugeBack, ui_event_btnGaugeBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnGaugeData, ui_event_btnGaugeData, LV_EVENT_ALL, NULL);
    uic_Gauges = ui_Gauges;
    uic_gVoltage = ui_gVoltage;
    uic_gVoltageValue = ui_gVoltageValue;
    uic_titVoltage = ui_titVoltage;
    uic_gAmpere = ui_gAmpere;
    uic_gAmpereValue = ui_gAmpereValue;
    uic_titAmpere = ui_titAmpere;
    uic_gRPM = ui_gRPM;
    uic_gRpmValue = ui_gRpmValue;
    uic_titRpm = ui_titRpm;
    uic_gPower = ui_gPower;
    uic_gPowerValue = ui_gPowerValue;
    uic_titPower = ui_titPower;
    uic_gWaterFlow = ui_gWaterFlow;
    uic_gWaterFlowValue = ui_gWaterFlowValue;
    uic_titWaterFlow = ui_titWaterFlow;
    uic_btnGaugeBack = ui_btnGaugeBack;
    uic_btnGaugeData = ui_btnGaugeData;

}

void ui_Gauges_screen_destroy(void)
{
    if(ui_Gauges) lv_obj_del(ui_Gauges);

    // NULL screen variables
    uic_Gauges = NULL;
    ui_Gauges = NULL;
    uic_gVoltage = NULL;
    ui_gVoltage = NULL;
    uic_gVoltageValue = NULL;
    ui_gVoltageValue = NULL;
    uic_titVoltage = NULL;
    ui_titVoltage = NULL;
    uic_gAmpere = NULL;
    ui_gAmpere = NULL;
    uic_gAmpereValue = NULL;
    ui_gAmpereValue = NULL;
    uic_titAmpere = NULL;
    ui_titAmpere = NULL;
    uic_gRPM = NULL;
    ui_gRPM = NULL;
    uic_gRpmValue = NULL;
    ui_gRpmValue = NULL;
    uic_titRpm = NULL;
    ui_titRpm = NULL;
    uic_gPower = NULL;
    ui_gPower = NULL;
    uic_gPowerValue = NULL;
    ui_gPowerValue = NULL;
    uic_titPower = NULL;
    ui_titPower = NULL;
    uic_gWaterFlow = NULL;
    ui_gWaterFlow = NULL;
    uic_gWaterFlowValue = NULL;
    ui_gWaterFlowValue = NULL;
    uic_titWaterFlow = NULL;
    ui_titWaterFlow = NULL;
    uic_btnGaugeBack = NULL;
    ui_btnGaugeBack = NULL;
    ui_Label6 = NULL;
    uic_btnGaugeData = NULL;
    ui_btnGaugeData = NULL;
    ui_Label5 = NULL;

}
