// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: DataGathering

#ifndef UI_MAINMENU_H
#define UI_MAINMENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainMenu
extern void ui_MainMenu_screen_init(void);
extern void ui_MainMenu_screen_destroy(void);
extern lv_obj_t * ui_MainMenu;
extern lv_obj_t * ui_nav;
extern void ui_event_btnSettings(lv_event_t * e);
extern lv_obj_t * ui_btnSettings;
extern lv_obj_t * ui_Label3;
extern void ui_event_btnData(lv_event_t * e);
extern lv_obj_t * ui_btnData;
extern lv_obj_t * ui_Label2;
extern void ui_event_btnGauges(lv_event_t * e);
extern lv_obj_t * ui_btnGauges;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_label;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_lblErrorStartUp;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MainMenu;
extern lv_obj_t * uic_btnSettings;
extern lv_obj_t * uic_btnData;
extern lv_obj_t * uic_btnGauges;
extern lv_obj_t * uic_lblErrorStartUp;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

