// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: DataGathering

#include "ui.h"

lv_obj_t * uic_btnGauges;
lv_obj_t * uic_btnData;
lv_obj_t * uic_btnSettings;
lv_obj_t * uic_MainMenu;
lv_obj_t * ui_MainMenu = NULL;
lv_obj_t * ui_nav = NULL;
lv_obj_t * ui_btnSettings = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_btnData = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_btnGauges = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_label = NULL;
lv_obj_t * ui_logo = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_btnSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Settings_screen_init);
    }
}

void ui_event_btnData(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Data, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Data_screen_init);
    }
}

void ui_event_btnGauges(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Gauges, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Gauges_screen_init);
    }
}

// build funtions

void ui_MainMenu_screen_init(void)
{
    ui_MainMenu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainMenu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_nav = lv_obj_create(ui_MainMenu);
    lv_obj_remove_style_all(ui_nav);
    lv_obj_set_width(ui_nav, 954);
    lv_obj_set_height(ui_nav, 148);
    lv_obj_set_x(ui_nav, 0);
    lv_obj_set_y(ui_nav, 130);
    lv_obj_set_align(ui_nav, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_nav, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSettings = lv_button_create(ui_nav);
    lv_obj_set_width(ui_btnSettings, 250);
    lv_obj_set_height(ui_btnSettings, 100);
    lv_obj_set_x(ui_btnSettings, 290);
    lv_obj_set_y(ui_btnSettings, 0);
    lv_obj_set_align(ui_btnSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSettings, lv_color_hex(0xD34D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnSettings, lv_color_hex(0x891818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnSettings, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSettings, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettings, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnSettings, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnSettings, lv_color_hex(0xAD7171), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnSettings, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnSettings, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnSettings, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_btnSettings, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_btnSettings, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btnSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_btnSettings, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_btnSettings, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_btnSettings);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "SETTINGS");

    ui_btnData = lv_button_create(ui_nav);
    lv_obj_set_width(ui_btnData, 250);
    lv_obj_set_height(ui_btnData, 100);
    lv_obj_set_align(ui_btnData, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnData, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnData, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnData, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnData, lv_color_hex(0xD34D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnData, lv_color_hex(0x891818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnData, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnData, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnData, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnData, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnData, lv_color_hex(0xAD7171), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnData, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnData, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnData, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_btnData, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_btnData, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btnData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_btnData, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_btnData, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_btnData);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "DATA");

    ui_btnGauges = lv_button_create(ui_nav);
    lv_obj_set_width(ui_btnGauges, 250);
    lv_obj_set_height(ui_btnGauges, 100);
    lv_obj_set_x(ui_btnGauges, -290);
    lv_obj_set_y(ui_btnGauges, 0);
    lv_obj_set_align(ui_btnGauges, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnGauges, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnGauges, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnGauges, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnGauges, lv_color_hex(0xD34D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnGauges, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnGauges, lv_color_hex(0x891818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnGauges, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnGauges, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnGauges, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnGauges, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnGauges, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnGauges, lv_color_hex(0xAD7171), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnGauges, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnGauges, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnGauges, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_btnGauges, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_btnGauges, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnGauges, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btnGauges, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_btnGauges, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_btnGauges, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_btnGauges);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "GAUGES");

    ui_label = lv_obj_create(ui_MainMenu);
    lv_obj_remove_style_all(ui_label);
    lv_obj_set_width(ui_label, 800);
    lv_obj_set_height(ui_label, 300);
    lv_obj_set_x(ui_label, 0);
    lv_obj_set_y(ui_label, -131);
    lv_obj_set_align(ui_label, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_label, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_logo = lv_image_create(ui_label);
    lv_image_set_src(ui_logo, &ui_img_1396634952);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo, 0);
    lv_obj_set_y(ui_logo, -50);
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_label);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 100);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "WATER TURBINE MACHINE");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnSettings, ui_event_btnSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnData, ui_event_btnData, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnGauges, ui_event_btnGauges, LV_EVENT_ALL, NULL);
    uic_MainMenu = ui_MainMenu;
    uic_btnSettings = ui_btnSettings;
    uic_btnData = ui_btnData;
    uic_btnGauges = ui_btnGauges;

}

void ui_MainMenu_screen_destroy(void)
{
    if(ui_MainMenu) lv_obj_del(ui_MainMenu);

    // NULL screen variables
    uic_MainMenu = NULL;
    ui_MainMenu = NULL;
    ui_nav = NULL;
    uic_btnSettings = NULL;
    ui_btnSettings = NULL;
    ui_Label3 = NULL;
    uic_btnData = NULL;
    ui_btnData = NULL;
    ui_Label2 = NULL;
    uic_btnGauges = NULL;
    ui_btnGauges = NULL;
    ui_Label1 = NULL;
    ui_label = NULL;
    ui_logo = NULL;
    ui_Label4 = NULL;

}
