// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: DataGathering

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_SettingsContainer;
extern lv_obj_t * ui_lblCurrentSettings;
extern lv_obj_t * ui_txtbSettingsCurrentValue;
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_btnSettingsNext;
extern lv_obj_t * ui_Label10;
extern void ui_event_btnSettingsSave(lv_event_t * e);
extern lv_obj_t * ui_btnSettingsSave;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_btnSettingsBack;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Settings;
extern lv_obj_t * uic_SettingsContainer;
extern lv_obj_t * uic_lblCurrentSettings;
extern lv_obj_t * uic_txtbSettingsCurrentValue;
extern lv_obj_t * uic_btnSettingsNext;
extern lv_obj_t * uic_btnSettingsSave;
extern lv_obj_t * uic_btnSettingsBack;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

