// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: DataGathering

#include "ui.h"

lv_obj_t * uic_btnSettingsBack;
lv_obj_t * uic_btnSettingsSave;
lv_obj_t * uic_btnSettingsNext;
lv_obj_t * uic_txtbSettingsCurrentValue;
lv_obj_t * uic_lblCurrentSettings;
lv_obj_t * uic_SettingsContainer;
lv_obj_t * uic_Settings;
lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_SettingsContainer = NULL;
lv_obj_t * ui_lblCurrentSettings = NULL;
lv_obj_t * ui_txtbSettingsCurrentValue = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_btnSettingsNext = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_btnSettingsSave = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_btnSettingsBack = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions
void ui_event_btnSettingsSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainMenu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainMenu_screen_init);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Settings, &ui_img_1396634952, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_opa(ui_Settings, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -220);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "SETTINGS PAGE");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsContainer = lv_obj_create(ui_Settings);
    lv_obj_remove_style_all(ui_SettingsContainer);
    lv_obj_set_width(ui_SettingsContainer, 299);
    lv_obj_set_height(ui_SettingsContainer, 145);
    lv_obj_set_x(ui_SettingsContainer, -298);
    lv_obj_set_y(ui_SettingsContainer, -83);
    lv_obj_set_align(ui_SettingsContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblCurrentSettings = lv_label_create(ui_SettingsContainer);
    lv_obj_set_width(ui_lblCurrentSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCurrentSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCurrentSettings, 0);
    lv_obj_set_y(ui_lblCurrentSettings, -30);
    lv_obj_set_align(ui_lblCurrentSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCurrentSettings, "FLOW RATE CALIBRATION");
    lv_obj_set_style_text_font(ui_lblCurrentSettings, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtbSettingsCurrentValue = lv_textarea_create(ui_SettingsContainer);
    lv_obj_set_width(ui_txtbSettingsCurrentValue, 256);
    lv_obj_set_height(ui_txtbSettingsCurrentValue, LV_SIZE_CONTENT);    /// 47
    lv_obj_set_x(ui_txtbSettingsCurrentValue, 0);
    lv_obj_set_y(ui_txtbSettingsCurrentValue, 30);
    lv_obj_set_align(ui_txtbSettingsCurrentValue, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtbSettingsCurrentValue, "Placeholder...");
    lv_textarea_set_one_line(ui_txtbSettingsCurrentValue, true);

    ui_Keyboard2 = lv_keyboard_create(ui_Settings);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, 624);
    lv_obj_set_height(ui_Keyboard2, 231);
    lv_obj_set_x(ui_Keyboard2, -124);
    lv_obj_set_y(ui_Keyboard2, 132);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);

    ui_btnSettingsNext = lv_button_create(ui_Settings);
    lv_obj_set_width(ui_btnSettingsNext, 173);
    lv_obj_set_height(ui_btnSettingsNext, 50);
    lv_obj_set_x(ui_btnSettingsNext, 230);
    lv_obj_set_y(ui_btnSettingsNext, -70);
    lv_obj_set_align(ui_btnSettingsNext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingsNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingsNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_btnSettingsNext);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "NEXT");

    ui_btnSettingsSave = lv_button_create(ui_Settings);
    lv_obj_set_width(ui_btnSettingsSave, 250);
    lv_obj_set_height(ui_btnSettingsSave, 100);
    lv_obj_set_x(ui_btnSettingsSave, 354);
    lv_obj_set_y(ui_btnSettingsSave, 211);
    lv_obj_set_align(ui_btnSettingsSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingsSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingsSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnSettingsSave, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSettingsSave, lv_color_hex(0xD34D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSettingsSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnSettingsSave, lv_color_hex(0x891818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnSettingsSave, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSettingsSave, lv_color_hex(0xB7B7B7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSettingsSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSettingsSave, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_btnSettingsSave, LV_BORDER_SIDE_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnSettingsSave, lv_color_hex(0xAD7171), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnSettingsSave, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_btnSettingsSave, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_btnSettingsSave, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_btnSettingsSave, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_btnSettingsSave, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_btnSettingsSave, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_btnSettingsSave, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_btnSettingsSave, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_btnSettingsSave, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_btnSettingsSave);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "SAVE");

    ui_btnSettingsBack = lv_button_create(ui_Settings);
    lv_obj_set_width(ui_btnSettingsBack, 173);
    lv_obj_set_height(ui_btnSettingsBack, 50);
    lv_obj_set_x(ui_btnSettingsBack, 0);
    lv_obj_set_y(ui_btnSettingsBack, -70);
    lv_obj_set_align(ui_btnSettingsBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSettingsBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSettingsBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_btnSettingsBack);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "BACK");

    lv_keyboard_set_textarea(ui_Keyboard2, ui_txtbSettingsCurrentValue);
    lv_obj_add_event_cb(ui_btnSettingsSave, ui_event_btnSettingsSave, LV_EVENT_ALL, NULL);
    uic_Settings = ui_Settings;
    uic_SettingsContainer = ui_SettingsContainer;
    uic_lblCurrentSettings = ui_lblCurrentSettings;
    uic_txtbSettingsCurrentValue = ui_txtbSettingsCurrentValue;
    uic_btnSettingsNext = ui_btnSettingsNext;
    uic_btnSettingsSave = ui_btnSettingsSave;
    uic_btnSettingsBack = ui_btnSettingsBack;

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    uic_Settings = NULL;
    ui_Settings = NULL;
    ui_Label9 = NULL;
    uic_SettingsContainer = NULL;
    ui_SettingsContainer = NULL;
    uic_lblCurrentSettings = NULL;
    ui_lblCurrentSettings = NULL;
    uic_txtbSettingsCurrentValue = NULL;
    ui_txtbSettingsCurrentValue = NULL;
    ui_Keyboard2 = NULL;
    uic_btnSettingsNext = NULL;
    ui_btnSettingsNext = NULL;
    ui_Label10 = NULL;
    uic_btnSettingsSave = NULL;
    ui_btnSettingsSave = NULL;
    ui_Label7 = NULL;
    uic_btnSettingsBack = NULL;
    ui_btnSettingsBack = NULL;
    ui_Label11 = NULL;

}
